version: '3.7'
services:
  media-browser-frontend:
    build:
      context: ./client/
      dockerfile: Dockerfile
    container_name: media-app-frontend
    depends_on:
      - media-browser-backend
    links:
      - media-browser-backend
    expose:
      - '5173'
    ports:
      - 5173:3000
    volumes:
      - ./client:/app/frontend
      - ./pnpm-workspace.yaml:/app/pnpm-workspace.yaml
      - ./pnpm-lock.yaml:/app/pnpm-lock.yaml
    working_dir: /app/frontend
    command: pnpm dev
  media-browser-backend:
    build:
      context: ./server/
      dockerfile: Dockerfile
    container_name: media-app-backend
    volumes:
      - ./server:/app/server/
      - ./pnpm-workspace.yaml:/app/pnpm-workspace.yaml
      - ./pnpm-lock.yaml:/app/pnpm-lock.yaml
      - ./server/nodemon.json:/app/server/nodemon.json
    ports:
      - 3000:3000
    expose:
      - '3000'
    depends_on:
      - database
    links:
      - database
    working_dir: /app/server
    command: pnpm start
  database:
    container_name: postgres
    image: postgres
    environment:
      - POSTGRES_PASSWORD=123123
    ports:
      - 5432:5432
